language: node_js
node_js:
  - "10"
cache: yarn
git:
  quiet: true

install: yarn
script:
  - yarn run lint
  - yarn run test --coverage
  - yarn codecov
  - yarn run build

deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
