codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "75...100"

  status:
    project:
      default:
        target: 75%
    patch:
      default:
        target: 75%
    changes: no
